autoload -U compinit && compinit
autoload colors && colors

for file in ~/.zsh/*.zsh
do
  source $file
done

if [[ $(uname) == Darwin ]]; then
  source ~/.zsh/platform/darwin.zsh
elif [[ $(uname) == Linux ]]; then
  source ~/.zsh/platform/linux.zsh
fi

if [[ -s "$HOME/.rvm/scripts/rvm" ]]
then
  source "$HOME/.rvm/scripts/rvm"
fi

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
